chore: [sc-1877] Cleanup Commands Interface
blockjoy/api-proto pull request #111
Opened 2023-06-27 12:12 UTC by mjr-blockjoy

proto cleanup according to BB Meeting
Story details: https://app.shortcut.com/blockjoy/story/1877

2023-06-27 12:40 UTC, chrisabruce requested changes

2023-06-27 12:40 UTC, chrisabruce commented on blockjoy/v1/command.proto
>  message NodeDelete {
Don't we need the Node's id as well?

2023-06-27 12:40 UTC, chrisabruce commented on blockjoy/v1/command.proto
>  message NodeDelete {
Actually, this should be moved to `Node` proto as well?

2023-06-27 12:57 UTC, mjr-blockjoy commented on blockjoy/v1/command.proto
>  message NodeDelete {
This one is part of  `NodeCommand` (line 95), which already has `node_id` and is sent from API to the Host

2023-06-29 12:05 UTC, ThouCheese commented on blockjoy/v1/command.proto
> +// Service providing commands to be executed on Host
on *a host

2023-06-29 12:08 UTC, ThouCheese commented on blockjoy/v1/command.proto
> +  // This shall be used only by Host.
*hosts

2023-06-29 12:08 UTC, ThouCheese commented on blockjoy/v1/command.proto
> +  // This can be used by anyone, but primarily by Host.
*hosts

2023-06-29 13:41 UTC, ThouCheese approved these changes

2023-06-30 04:46 UTC, merged