feat: added rulesets
blockjoy/api-proto pull request #71
Opened 2023-03-27 09:47 UTC by tstaetter

2023-03-27 12:09 UTC, mjr-blockjoy commented on blockjoy/api/v1/node.proto
>    Policy policy = 2;
lets rename `Policy` to `Action`

2023-03-27 12:09 UTC, mjr-blockjoy commented on blockjoy/api/v1/node.proto
> +  optional Policy default_in = 8;
default_in/out and fallback actions when packet doesn't match any rule, so it doesn't make sense to put it into every rule(even optional)

2023-03-29 09:32 UTC, mjr-blockjoy commented on blockjoy/api/v1/node.proto
>  message NodeFirewallUpdate {
This one is used in line 157 (command sent to BV). I think we should always send the same message to BV, both on create and in firewall update command, and id should be `FirewallConfiguration`.

2023-03-30 19:17 UTC, densone requested changes
rename ruleset back to policy in all code.

2023-04-04 17:59 UTC, closed without merging