Feat/merge apis
blockjoy/api-proto pull request #76
Opened 2023-03-30 14:22 UTC by ThouCheese

2023-04-17 16:33 UTC, tstaetter commented on blockjoy/api/ui_v1/authentication_service.proto
> -  rpc Refresh(RefreshTokenRequest) returns (RefreshTokenResponse);
refresh isn't used atm

2023-04-17 16:33 UTC, tstaetter commented on blockjoy/api/ui_v1/billing_service.proto
> -syntax = "proto3";
i guess we can skip all the service for now

2023-04-17 16:37 UTC, tstaetter commented on public/v1/blockchain.proto
> +  bool supports_broadcast = 13;
do we still need those?

2023-04-17 22:22 UTC, tstaetter commented on public/v1/organization.proto
> +  rpc Leave(LeaveOrgRequest) returns (google.protobuf.Empty);
aren't those the same with just different privileges?

2023-04-17 22:23 UTC, tstaetter approved these changes

2023-04-17 22:26 UTC, ThouCheese commented on public/v1/organization.proto
> +  rpc Leave(LeaveOrgRequest) returns (google.protobuf.Empty);
Eh it is just a rename, Chris thought that Org was more dev-friendly than making people type out Organization

2023-04-17 22:27 UTC, ThouCheese commented on public/v1/dashboard.proto
Gone

2023-04-17 22:27 UTC, ThouCheese commented on public/v1/command.proto
> +message CreateCommandRequest {
It says in the doc comment that the other commands have to be created in other ways, and it gives an example of such a way

2023-04-17 22:28 UTC, ThouCheese commented on public/v1/billing.proto
Gone

2023-04-17 22:31 UTC, ThouCheese commented on blockjoy/api/ui_v1/authentication_service.proto
> -  rpc Refresh(RefreshTokenRequest) returns (RefreshTokenResponse);
I think that we will start using it soon

2023-04-18 09:21 UTC, chrisabruce commented on public/v1/host.proto
> +  optional uint64 disk_size_bytes = 7;
Yes love it!

2023-04-18 09:23 UTC, chrisabruce requested changes

2023-04-18 09:23 UTC, chrisabruce commented on public/v1/command.proto
> +  // typically look different from those that go to a host.
This will be public in the api docs. We should make this a little more public friendly. Possibly remove the last sentence about the reason...

2023-04-18 12:13 UTC, merged