Feat/node states
blockjoy/api-proto pull request #8
Opened 2022-08-11 20:47 UTC by tstaetter

added staking status, moved app_status, container_status out of NodeStatus, removed NodeStatus type

2022-08-11 20:53 UTC, loony-bean commented on blockjoy/api/v1/node_types.proto
> +  Type type = 5;
I keep forgetting why we need that type here.. we are inside of NodeType, so it's a Node, no?

2022-08-11 21:10 UTC, loony-bean commented on blockjoy/api/v1/node_types.proto
>      Validating = 4;
Sean also said we need a status like `Unstaked` aka `Deleted`, as opposite to `Staked`

2022-08-12 15:36 UTC, zeenix approved these changes
lgtlm

2022-08-12 15:48 UTC, chrisabruce requested changes

2022-08-12 15:48 UTC, chrisabruce commented on blockjoy/api/v1/node.proto
>      Uuid node_id = 1;
should this not be just `id`? Since it already has a parent called `NodeInfo`, seems better to see `node_info.id` instead of `node_info.node_id`.

2022-08-12 16:13 UTC, chrisabruce approved these changes

2022-08-12 16:13 UTC, merged