Feat/UI api
blockjoy/api-proto pull request #9
Opened 2022-08-22 20:00 UTC by tstaetter

First version of protos used for UI. I tried to stick to the current RESTful API where appropriate, the rest is basically a guess of what we need for the beta.

2022-08-23 19:48 UTC, frontend-joe requested changes
Looking good my bro

2022-08-23 19:48 UTC, frontend-joe commented on blockjoy/api/ui_v1/node_service.proto
> +
We should add a GetNodeStats or GetNodeDashboardStats method so we can display statistics on the dashboard page. Ideally these stats would be total counts for each node status - total, online, disabled, syncing etc. 

From the frontend point of view, it would be great if these were served up as an array like this:

```
[ 
  { 
    name: "Nodes", 
    value: 49 
  },
  { 
    name: "Online", 
    value: 15
  }
  ...
 ]
```

2022-08-23 19:48 UTC, frontend-joe commented on blockjoy/api/ui_v1/user_service.proto
> +
Not an urgent requirement as yet, but longer term it would be great if we could add a UserConfigService - so that the frontend could allow the user to configure their block visor app and be consistent across all of their devices. We want accessibility to be paramount so I guess this goes hand in hand with that!

2022-08-25 09:17 UTC, chrisabruce requested changes

2022-08-25 09:17 UTC, chrisabruce commented on blockjoy/api/ui_v1/common.proto
> +  }
Not quite sure what this is, but should it have some kind of value field? 'KPI' stands for Key Performance Indicator, so would assume this is a measured metric.

2022-08-25 09:17 UTC, chrisabruce commented on blockjoy/api/ui_v1/common.proto
> +}
Can you describe thoughts about what this does? Is this just config vars for web site? Assuming these don't appear to be attached to any specific user? If not, then maybe change to `AppConfigurationParameter` or we usually do something called `AppSettings` or `AppConfig`

2022-08-25 09:17 UTC, chrisabruce commented on blockjoy/api/ui_v1/node_service.proto
> +
We might want this at an Org level?

2022-08-25 10:44 UTC, tstaetter commented on blockjoy/api/ui_v1/common.proto
> +  optional Uuid id = 1;
we keep those fields optional for Node, Host, Organization so we can use the same message type for creation and retrieving

2022-08-25 10:45 UTC, tstaetter commented on blockjoy/api/ui_v1/fe_host_service.proto
> +}
yes, if the method could return an array, the array is returned for a single item as well

2022-08-25 10:47 UTC, tstaetter commented on blockjoy/api/ui_v1/common.proto
> +  }
we have the value of type Any in the type. the name enum is there to ensure that only "valid" KPIs are used.

2022-08-25 10:49 UTC, tstaetter commented on blockjoy/api/ui_v1/common.proto
> +}
The idea is to create an array of such parameters used to store user preferences of the frontend, e.g. colors etc. The preferences should be stored per user

2022-08-25 10:51 UTC, tstaetter commented on blockjoy/api/ui_v1/fe_host_service.proto
> +}
yes, the messages array should be used for something like that

2022-08-25 10:52 UTC, tstaetter commented on blockjoy/api/ui_v1/common.proto
> +  optional int32 count = 4;
u mean the ``` count ``` field?

2022-08-25 11:57 UTC, chrisabruce commented on blockjoy/api/ui_v1/common.proto
> +  optional int32 count = 4;
Yes think this should be renamed `limit` it is very common term for limiting the result back. `count` is too generic.

2022-08-25 11:59 UTC, chrisabruce commented on blockjoy/api/ui_v1/common.proto
> +}
if per user, then I would suggest adding the users id, and just making this an array. We can store in db as a comma separated list of key/values?

2022-08-25 12:33 UTC, frontend-joe approved these changes
Stubs looking good!

2022-08-25 12:37 UTC, tstaetter commented on blockjoy/api/ui_v1/common.proto
> +}
added user_id in the request type

2022-08-25 14:33 UTC, merged